name: DEV

on:
  push:
    branches:
      - main
   
permissions:
  id-token: write   # required for OIDC
  contents: read    # allow reading the repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    env:
      STAGE: dev

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses : actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install correct Yarn version
        run: corepack prepare yarn@4.10.3 --activate

      - name: Install dependencies
        run: yarn
          
      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Build project
        run: yarn build

      - name: CDK synthetize
        run: cdk synth

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
